Setting clientUri in ToOidcSynchronizer
CESNET/spreg_oidc_metadata_sync pull request #6
Opened 2021-07-02 09:02 UTC by BaranekD

2021-07-08 07:04 UTC, vyskocilpavel approved these changes

2021-07-12 10:32 UTC, dBucik requested changes

2021-07-12 10:32 UTC, dBucik commented on src/main/java/cz/muni/ics/oidc/ToOidcSynchronizer.java
> +import de.danielbechler.util.Strings;
Remove this import.

2021-07-12 10:32 UTC, dBucik commented on src/main/java/cz/muni/ics/oidc/ToOidcSynchronizer.java
> +                    Strings.hasText(attributeValue.valueAsMap().get("en"))) {
Replace the ```Strings.hasText(...)``` call with ```StringUtils.hasText``` from the Spring package.

2021-07-12 10:32 UTC, dBucik commented on src/main/java/cz/muni/ics/oidc/ToOidcSynchronizer.java
> +                    Strings.hasText(attributeValue.valueAsString())) {
Same as above

2021-07-12 10:32 UTC, dBucik commented on src/main/java/cz/muni/ics/oidc/props/AttrsMapping.java
> +        attrNames.addAll(homePageUris);
Probably better to check if the passed argument is not null, as in such a case the thing would break.

2021-07-29 06:00 UTC, dBucik approved these changes

2021-07-29 06:00 UTC, merged